spring:
  application:
    name: vote
  mail:
    host: smtp.gmail.com
    port: 587
    username: kahkian0630@gmail.com
    password: oprbegylrhssapok
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  ai:
    openai:
      api-key: sk-4a252bd04e3240c4b9eb52361da9efb2
      base-url: https://api.deepseek.com # point to DeepSeek's endpoint
      chat:
        options:
          model: deepseek-chat           # or deepseek-reasoner for R1
          temperature: 0.7

spring.datasource:
#  url: jdbc:postgresql://host.docker.internal:5432/your_quest  #jdbc:mysql://localhost:3306/vote
  url: jdbc:postgresql://db.jxuhngkqdqheyqujkjfo.supabase.co:5432/postgres?user=postgres&password=SEW_epwP6tDVwCi

  username: postgres  #root
  password: P@ssw0rd
  driver-class-name: org.postgresql.Driver

app:
  cors:
    allowed-origins: http://localhost:5173

token:
  jwt:
    secret: ${JWT_SECRET:5910e844-0dc4-11eb-adc1-0242ac120002}
  expiry: 5 #5 minutes (verification token)
  refresh:
    expiry-days: 7

frontend:
  url: ${FRONTEND_URL:http://localhost:8080}

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:682908466873-llntklr9v5ej7hl6t89nbvftu3lbg32j.apps.googleusercontent.com}
    client-secret: ${GOOGLE_CLIENT_SECRET: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}
