spring:
  application:
    name: vote
  mail:
    host: smtp.gmail.com
    port: 587
    username: kahkian0630@gmail.com
    password: oprbegylrhssapok
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

spring.datasource:
  url: jdbc:postgresql://localhost:5432/your_quest  #jdbc:mysql://localhost:3306/vote
  username: postgres  #root
  password: P@ssw0rd
  driver-class-name: org.postgresql.Driver

token:
  jwt:
    secret: 5910e844-0dc4-11eb-adc1-0242ac120002
  expiry: 5 #5 minutes

frontend:
  url: http://localhost:8080

google:
  oauth:
    client-id: 682908466873-llntklr9v5ej7hl6t89nbvftu3lbg32j.apps.googleusercontent.com
